services:
  murmansk-bot:
    #image: murmansk-tg:1
    build:
      context: .
      dockerfile: Dockerfile
    container_name: murmansk-bot
    restart: always
    volumes:
      - .env:/app/.env
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge