services:
  murmansk-bot:
    image: murmansk-tg:1
    container_name: murmansk-bot
    restart: always
    volumes:
      - .env:/app/.env
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge