services:
  murmansk-bot:
    build: .
    container_name: murmansk-bot
    restart: always
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    volumes:
      - ./data:/app/data
      - .env:/app/.env
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge