services:
  murmansk-bot:
    image: murmansk-tg:1
    container_name: murmansk-bot
    env_file: .env
    restart: always
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge