openapi: 3.0.0
info:
  title: Murmansk Bot Events API
  version: 0.1.0
paths:
  /set_date:
    post:
      summary: Add new event
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                date:
                  type: string
                  example: "12.12.2025"
                name:
                  type: string
                  example: "new_year"
      responses:
        '200':
          description: Event created
        '400':
          description: Invalid input
  /list:
    get:
      summary: List events
      responses:
        '200':
          description: List of events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
components:
  schemas:
    Event:
      type: object
      properties:
        name:
          type: string
        date:
          type: string
        status:
          type: string
        description:
          type: string
