name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    environment: master
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get branch name, date, and commit hash
      id: vars
      run: |
        echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV
        echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
        echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: reshkin/murmansk-bot:${{ env.BRANCH_NAME }}_${{ env.DATE }}_${{ env.COMMIT_HASH }}